version: '3.8'
services:
  nginx:
    image: nginx
    working_dir: /app
    volumes:
      - ./app:/app:rw,delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - php
    ports:
      - 80:80
  php:
    build: ./docker/php
    working_dir: /app
    volumes:
      - ./app:/app:rw,delegated
  mysql:
    image: mariadb # maria is faster and have better support
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guestbook
    ports:
      - 3306:3306
volumes:
  mysql:
